### ISSUE TITLE
Gravestone not spawning upon death

### ISSUE THREAD

**Issue by Mario0051** [Geometrically/Gravestones#1]
As title says. Even with items in the inventory. Using latest Gravestones mod version for 1.16.

**Comment by Geometrically** [comment]
Do you have gravestone spawning enabled in the config? Is keep inventory on?

**Comment by Mario0051** [comment]
Gravestone spawning is enabled and keep inventory is off.

**Comment by Geometrically** [comment]
I can't seem to reproduce this. Could you get a video of this happening?

**Comment by Mario0051** [comment]
It seems to happen randomly. Gravestones do sometime spawn but can likely not spawn.

**Comment by shikyo13** [comment]
I can report this happening as well on my server running Fabric Version: 0.6.1.45 and gravestones-1.4.0 . On at least 3 separate occasions other players or myself have not had a grave spawn upon death. In my case I was on a pillar of blocks with magma block and lava nearby so perhaps it was a case of not finding a suitable place to spawn. However the block I was on was safe.
