### ISSUE TITLE
Item in chestplate slot not being returned

### ISSUE THREAD

**Issue by BearFoxThirty** [Geometrically/Gravestones#10]
After I die I consistently do not get my iron chestplate back, it's the only thing absent that I can tell. So i just end up crafting another. I am using the trinkets mod by the way, which adds an elytra slot next to the chestplate slot. Otherwise great mod, although my friends complained if you die in the void the gravestone doesn't spawn at like y:10 or something.

**Comment by Geometrically** [comment]
Did not see this! I will look into this issue.

**Comment by Geometrically** [comment]
Could not reproduce, with the elytra and chest plate both on
