### ISSUE TITLE
Creepers destroying graves

### ISSUE THREAD

**Issue by PotatoPresident** [Geometrically/Gravestones#18]
I'm playing on the fabric SMP and twice now I've been blown up by a creeper and the explosion destroys the grave the spawns. The first time it got blown up and dropped a blank grave item that I can place and break with no loot. The second time it didn't seem to drop an item.

**Comment by Greatone123** [comment]
I have the same issue, creeper made the gravestone an item, I can't get my stuff back, I just keep picking up the gravestone.
