### ISSUE TITLE
Crashes when falling out of the world

### ISSUE THREAD

**Issue by comp500** [Geometrically/Gravestones#2]
Minecraft: 1.16.1
Gravestones: 1.3.1
The modpack used is AoF 3 1.1.1

See crash log https://paste.ee/p/u3dOs, seems to be thrown in https://github.com/Geometrically/Gravestones/blob/master/src/main/java/net/guavy/gravestones/Gravestones.java#L96 when it tries to place a block outside the world.

**Comment by Geometrically** [comment]
Will fix. What functionality would be better, not placing it at all? If not, where would it be placed?

**Comment by comp500** [comment]
I'd think you could just place it at y = 1, making sure to place it above bedrock if it is there.
