### ISSUE TITLE
Trinkets duped

### ISSUE THREAD

**Issue by Danklor** [Geometrically/Gravestones#7]
While testing Gravestones with Trinkets and Bunch o' Trinkets I found an item duplication issue.  On death with full inventory, armor, and trinket slots, all items were correctly placed in the gravestone.  However the trinkets were also dropped on the ground.  On returning to the gravestone I was able to retrieve all the items as expected, but the duplicate trinkets were also on the ground to pick up.

**Comment by Geometrically** [comment]
I see the problem, will fix this in the latest patch
