### ISSUE TITLE
Feature request: An eye of ender-like item to find your nearest grave

### ISSUE THREAD

**Issue by Katorone** [Geometrically/Gravestones#8]
Players on my server are exploring and dying far from home.  They often just have a guess of the general direction their grave would be in.

Would it be possible to add an item that lets players find their nearest grave?  From a gameplay perspective, i would love if this comes with a cost.  A crafting cost and/or a usage cost.  An item like the eye of ender comes to mind, where its cost to use is a potential chance for it being destroyed after use.  In this example, the crafting recipe could be an enderpearl and a bone.

If this is out of the scope for the mod, would you consider adding a line to the log each time a grave is spawned, with its coordinates?  That way we can guide our players to the general area of their graves manually.

**Comment by Geometrically** [comment]
I added a console message in my latest commit, in the future I'll look into an item for this

**Comment by Katorone** [comment]
Thank you!
